# ==============================================================================
# 손절 / 익절 기준 (Stop-Loss / Take-Profit Rules)
# ==============================================================================
profit_loss:
  # 기본 손절매 비율 (%)
  stop_loss_percentage: -3.0

  # 기본 익절 비율 (%)
  take_profit_percentage: 5.0

  # 트레일링 스탑 (Trailing Stop) 설정
  trailing_stop:
    enabled: True
    # 고점 대비 하락률 (%)
    drawdown_percentage: 2.0

# ==============================================================================
# 포지션 크기 설정 (Position Sizing)
# ==============================================================================
position_sizing:
  # 계좌 총 자산 대비 최대 비중 (%)
  max_portion_per_stock: 20.0

  # 위험 기반 포지션 크기 조절
  risk_based_sizing:
    enabled: False
    strategy: "fixed_fractional"
    fraction: 10.0

# ==============================================================================
# 거래 시간 설정 (Trading Hours)
# ==============================================================================
trading_hours:
  # 거래 시작 시간 (HH:MM:SS)
  market_open: "09:00:00"

  # 신규 매수 마감 시간 (HH:MM:SS)
  new_buy_close: "15:00:00"

  # 장 마감 시간 (HH:MM:SS)
  market_close: "15:30:00"

  # 당일 청산 시간 (HH:MM:SS)
  day_trading_close: "15:20:00"

  # 당일 청산 기능 활성화 여부
  enable_day_trading_close: false

# ==============================================================================
# 리스크 관리 (Risk Management)
# ==============================================================================
risk_management:
  # 최대 보유 포지션 수
  max_positions: 10

  # 종목별 최대 투자 비중 (%)
  max_position_size_pct: 20.0

  # 동시 손실 종목 수 제한
  max_simultaneous_losses: 3
